#pragma once

#include "lvgl/lvgl.h"
#include <stdint.h>

// One Pokédex record. The table is generated by generate.py and lives entirely
// in flash so the view works without any network access.
typedef struct {
  uint16_t number;    // National Pokédex number
  const char *name;   // Display name, e.g. "Farfetch’d"
  const char *genus;  // e.g. "Mouse Pokémon"
  const char *types;  // e.g. "Grass · Poison"
  const char *entry;  // Pokédex flavor text
  uint16_t height_dm; // Height in decimetres
  uint16_t weight_hg; // Weight in hectograms
  uint8_t hp;
  uint8_t attack;
  uint8_t defense;
  uint8_t special_attack;
  uint8_t special_defense;
  uint8_t speed;
  const lv_image_dsc_t *sprite; // 1-bit sprite, see pokemon_sprites.c
} pokemon_entry_t;

extern const pokemon_entry_t pokemon_entries[];
extern const uint16_t pokemon_entries_count;
extern const lv_image_dsc_t pokemon_sprites[];
