//
// GENERATED FILE - do not edit by hand.
// Regenerate with: python3 pokemon/generate.py
// Data and sprites courtesy of PokéAPI (https://pokeapi.co).
//

#include "pokemon_data.h"

const pokemon_entry_t pokemon_entries[] = {
    {
        .number = 1,
        .name = "Bulbasaur",
        .genus = "Seed Pokémon",
        .types = "Grass · Poison",
        .entry = "A strange seed was planted on its back at birth. The plant "
                 "sprouts and grows with this POKéMON.",
        .height_dm = 7,
        .weight_hg = 69,
        .hp = 45,
        .attack = 49,
        .defense = 49,
        .special_attack = 65,
        .special_defense = 65,
        .speed = 45,
        .sprite = &pokemon_sprites[0],
    },
    {
        .number = 2,
        .name = "Ivysaur",
        .genus = "Seed Pokémon",
        .types = "Grass · Poison",
        .entry = "When the bulb on its back grows large, it appears to lose "
                 "the ability to stand on its hind legs.",
        .height_dm = 10,
        .weight_hg = 130,
        .hp = 60,
        .attack = 62,
        .defense = 63,
        .special_attack = 80,
        .special_defense = 80,
        .speed = 60,
        .sprite = &pokemon_sprites[1],
    },
    {
        .number = 3,
        .name = "Venusaur",
        .genus = "Seed Pokémon",
        .types = "Grass · Poison",
        .entry = "The plant blooms when it is absorbing solar energy. It stays "
                 "on the move to seek sunlight.",
        .height_dm = 20,
        .weight_hg = 1000,
        .hp = 80,
        .attack = 82,
        .defense = 83,
        .special_attack = 100,
        .special_defense = 100,
        .speed = 80,
        .sprite = &pokemon_sprites[2],
    },
    {
        .number = 4,
        .name = "Charmander",
        .genus = "Lizard Pokémon",
        .types = "Fire",
        .entry = "Obviously prefers hot places. When it rains, steam is said "
                 "to spout from the tip of its tail.",
        .height_dm = 6,
        .weight_hg = 85,
        .hp = 39,
        .attack = 52,
        .defense = 43,
        .special_attack = 60,
        .special_defense = 50,
        .speed = 65,
        .sprite = &pokemon_sprites[3],
    },
    {
        .number = 5,
        .name = "Charmeleon",
        .genus = "Flame Pokémon",
        .types = "Fire",
        .entry = "When it swings its burning tail, it elevates the temperature "
                 "to unbearably high levels.",
        .height_dm = 11,
        .weight_hg = 190,
        .hp = 58,
        .attack = 64,
        .defense = 58,
        .special_attack = 80,
        .special_defense = 65,
        .speed = 80,
        .sprite = &pokemon_sprites[4],
    },
    {
        .number = 6,
        .name = "Charizard",
        .genus = "Flame Pokémon",
        .types = "Fire · Flying",
        .entry = "Spits fire that is hot enough to melt boulders. Known to "
                 "cause forest fires unintentionally.",
        .height_dm = 17,
        .weight_hg = 905,
        .hp = 78,
        .attack = 84,
        .defense = 78,
        .special_attack = 109,
        .special_defense = 85,
        .speed = 100,
        .sprite = &pokemon_sprites[5],
    },
    {
        .number = 7,
        .name = "Squirtle",
        .genus = "Tiny Turtle Pokémon",
        .types = "Water",
        .entry = "After birth, its back swells and hardens into a shell. "
                 "Powerfully sprays foam from its mouth.",
        .height_dm = 5,
        .weight_hg = 90,
        .hp = 44,
        .attack = 48,
        .defense = 65,
        .special_attack = 50,
        .special_defense = 64,
        .speed = 43,
        .sprite = &pokemon_sprites[6],
    },
    {
        .number = 8,
        .name = "Wartortle",
        .genus = "Turtle Pokémon",
        .types = "Water",
        .entry = "Often hides in water to stalk unwary prey. For swimming "
                 "fast, it moves its ears to maintain balance.",
        .height_dm = 10,
        .weight_hg = 225,
        .hp = 59,
        .attack = 63,
        .defense = 80,
        .special_attack = 65,
        .special_defense = 80,
        .speed = 58,
        .sprite = &pokemon_sprites[7],
    },
    {
        .number = 9,
        .name = "Blastoise",
        .genus = "Shellfish Pokémon",
        .types = "Water",
        .entry = "A brutal POKéMON with pressurized water jets on its shell. "
                 "They are used for high speed tackles.",
        .height_dm = 16,
        .weight_hg = 855,
        .hp = 79,
        .attack = 83,
        .defense = 100,
        .special_attack = 85,
        .special_defense = 105,
        .speed = 78,
        .sprite = &pokemon_sprites[8],
    },
    {
        .number = 10,
        .name = "Caterpie",
        .genus = "Worm Pokémon",
        .types = "Bug",
        .entry = "Its short feet are tipped with suction pads that enable it "
                 "to tirelessly climb slopes and walls.",
        .height_dm = 3,
        .weight_hg = 29,
        .hp = 45,
        .attack = 30,
        .defense = 35,
        .special_attack = 20,
        .special_defense = 20,
        .speed = 45,
        .sprite = &pokemon_sprites[9],
    },
    {
        .number = 11,
        .name = "Metapod",
        .genus = "Cocoon Pokémon",
        .types = "Bug",
        .entry = "This POKéMON is vulnerable to attack while its shell is "
                 "soft, exposing its weak and tender body.",
        .height_dm = 7,
        .weight_hg = 99,
        .hp = 50,
        .attack = 20,
        .defense = 55,
        .special_attack = 25,
        .special_defense = 25,
        .speed = 30,
        .sprite = &pokemon_sprites[10],
    },
    {
        .number = 12,
        .name = "Butterfree",
        .genus = "Butterfly Pokémon",
        .types = "Bug · Flying",
        .entry = "In battle, it flaps its wings at high speed to release "
                 "highly toxic dust into the air.",
        .height_dm = 11,
        .weight_hg = 320,
        .hp = 60,
        .attack = 45,
        .defense = 50,
        .special_attack = 90,
        .special_defense = 80,
        .speed = 70,
        .sprite = &pokemon_sprites[11],
    },
    {
        .number = 13,
        .name = "Weedle",
        .genus = "Hairy Bug Pokémon",
        .types = "Bug · Poison",
        .entry = "Often found in forests, eating leaves. It has a sharp "
                 "venomous stinger on its head.",
        .height_dm = 3,
        .weight_hg = 32,
        .hp = 40,
        .attack = 35,
        .defense = 30,
        .special_attack = 20,
        .special_defense = 20,
        .speed = 50,
        .sprite = &pokemon_sprites[12],
    },
    {
        .number = 14,
        .name = "Kakuna",
        .genus = "Cocoon Pokémon",
        .types = "Bug · Poison",
        .entry = "Almost incapable of moving, this POKéMON can only harden its "
                 "shell to protect itself from predators.",
        .height_dm = 6,
        .weight_hg = 100,
        .hp = 45,
        .attack = 25,
        .defense = 50,
        .special_attack = 25,
        .special_defense = 25,
        .speed = 35,
        .sprite = &pokemon_sprites[13],
    },
    {
        .number = 15,
        .name = "Beedrill",
        .genus = "Poison Bee Pokémon",
        .types = "Bug · Poison",
        .entry = "Flies at high speed and attacks using its large venomous "
                 "stingers on its forelegs and tail.",
        .height_dm = 10,
        .weight_hg = 295,
        .hp = 65,
        .attack = 90,
        .defense = 40,
        .special_attack = 45,
        .special_defense = 80,
        .speed = 75,
        .sprite = &pokemon_sprites[14],
    },
    {
        .number = 16,
        .name = "Pidgey",
        .genus = "Tiny Bird Pokémon",
        .types = "Normal · Flying",
        .entry = "A common sight in forests and woods. It flaps its wings at "
                 "ground level to kick up blinding sand.",
        .height_dm = 3,
        .weight_hg = 18,
        .hp = 40,
        .attack = 45,
        .defense = 40,
        .special_attack = 35,
        .special_defense = 35,
        .speed = 56,
        .sprite = &pokemon_sprites[15],
    },
    {
        .number = 17,
        .name = "Pidgeotto",
        .genus = "Bird Pokémon",
        .types = "Normal · Flying",
        .entry = "Very protective of its sprawling territorial area, this "
                 "POKéMON will fiercely peck at any intruder.",
        .height_dm = 11,
        .weight_hg = 300,
        .hp = 63,
        .attack = 60,
        .defense = 55,
        .special_attack = 50,
        .special_defense = 50,
        .speed = 71,
        .sprite = &pokemon_sprites[16],
    },
    {
        .number = 18,
        .name = "Pidgeot",
        .genus = "Bird Pokémon",
        .types = "Normal · Flying",
        .entry = "When hunting, it skims the surface of water at high speed to "
                 "pick off unwary prey such as MAGIKARP.",
        .height_dm = 15,
        .weight_hg = 395,
        .hp = 83,
        .attack = 80,
        .defense = 75,
        .special_attack = 70,
        .special_defense = 70,
        .speed = 101,
        .sprite = &pokemon_sprites[17],
    },
    {
        .number = 19,
        .name = "Rattata",
        .genus = "Mouse Pokémon",
        .types = "Normal",
        .entry = "Bites anything when it attacks. Small and very quick, it is "
                 "a common sight in many places.",
        .height_dm = 3,
        .weight_hg = 35,
        .hp = 30,
        .attack = 56,
        .defense = 35,
        .special_attack = 25,
        .special_defense = 35,
        .speed = 72,
        .sprite = &pokemon_sprites[18],
    },
    {
        .number = 20,
        .name = "Raticate",
        .genus = "Mouse Pokémon",
        .types = "Normal",
        .entry = "It uses its whis kers to maintain its balance. It apparently "
                 "slows down if they are cut off.",
        .height_dm = 7,
        .weight_hg = 185,
        .hp = 55,
        .attack = 81,
        .defense = 60,
        .special_attack = 50,
        .special_defense = 70,
        .speed = 97,
        .sprite = &pokemon_sprites[19],
    },
    {
        .number = 21,
        .name = "Spearow",
        .genus = "Tiny Bird Pokémon",
        .types = "Normal · Flying",
        .entry = "Eats bugs in grassy areas. It has to flap its short wings at "
                 "high speed to stay airborne.",
        .height_dm = 3,
        .weight_hg = 20,
        .hp = 40,
        .attack = 60,
        .defense = 30,
        .special_attack = 31,
        .special_defense = 31,
        .speed = 70,
        .sprite = &pokemon_sprites[20],
    },
    {
        .number = 22,
        .name = "Fearow",
        .genus = "Beak Pokémon",
        .types = "Normal · Flying",
        .entry = "With its huge and magnificent wings, it can keep aloft "
                 "without ever having to land for rest.",
        .height_dm = 12,
        .weight_hg = 380,
        .hp = 65,
        .attack = 90,
        .defense = 65,
        .special_attack = 61,
        .special_defense = 61,
        .speed = 100,
        .sprite = &pokemon_sprites[21],
    },
    {
        .number = 23,
        .name = "Ekans",
        .genus = "Snake Pokémon",
        .types = "Poison",
        .entry = "Moves silently and stealthily. Eats the eggs of birds, such "
                 "as PIDGEY and SPEAROW, whole.",
        .height_dm = 20,
        .weight_hg = 69,
        .hp = 35,
        .attack = 60,
        .defense = 44,
        .special_attack = 40,
        .special_defense = 54,
        .speed = 55,
        .sprite = &pokemon_sprites[22],
    },
    {
        .number = 24,
        .name = "Arbok",
        .genus = "Cobra Pokémon",
        .types = "Poison",
        .entry = "It is rumored that the ferocious warning markings on its "
                 "belly differ from area to area.",
        .height_dm = 35,
        .weight_hg = 650,
        .hp = 60,
        .attack = 95,
        .defense = 69,
        .special_attack = 65,
        .special_defense = 79,
        .speed = 80,
        .sprite = &pokemon_sprites[23],
    },
    {
        .number = 25,
        .name = "Pikachu",
        .genus = "Mouse Pokémon",
        .types = "Electric",
        .entry = "When several of these POKéMON gather, their electricity "
                 "could build and cause lightning storms.",
        .height_dm = 4,
        .weight_hg = 60,
        .hp = 35,
        .attack = 55,
        .defense = 40,
        .special_attack = 50,
        .special_defense = 50,
        .speed = 90,
        .sprite = &pokemon_sprites[24],
    },
    {
        .number = 26,
        .name = "Raichu",
        .genus = "Mouse Pokémon",
        .types = "Electric",
        .entry = "Its long tail serves as a ground to protect itself from its "
                 "own high voltage power.",
        .height_dm = 8,
        .weight_hg = 300,
        .hp = 60,
        .attack = 90,
        .defense = 55,
        .special_attack = 90,
        .special_defense = 80,
        .speed = 110,
        .sprite = &pokemon_sprites[25],
    },
    {
        .number = 27,
        .name = "Sandshrew",
        .genus = "Mouse Pokémon",
        .types = "Ground",
        .entry = "Burrows deep underground in arid locations far from water. "
                 "It only emerges to hunt for food.",
        .height_dm = 6,
        .weight_hg = 120,
        .hp = 50,
        .attack = 75,
        .defense = 85,
        .special_attack = 20,
        .special_defense = 30,
        .speed = 40,
        .sprite = &pokemon_sprites[26],
    },
    {
        .number = 28,
        .name = "Sandslash",
        .genus = "Mouse Pokémon",
        .types = "Ground",
        .entry = "Curls up into a spiny ball when threatened. It can roll "
                 "while curled up to attack or escape.",
        .height_dm = 10,
        .weight_hg = 295,
        .hp = 75,
        .attack = 100,
        .defense = 110,
        .special_attack = 45,
        .special_defense = 55,
        .speed = 65,
        .sprite = &pokemon_sprites[27],
    },
    {
        .number = 29,
        .name = "Nidoran♀",
        .genus = "Poison Pin Pokémon",
        .types = "Poison",
        .entry = "Although small, its venomous barbs render this POKéMON "
                 "dangerous. The female has smaller horns.",
        .height_dm = 4,
        .weight_hg = 70,
        .hp = 55,
        .attack = 47,
        .defense = 52,
        .special_attack = 40,
        .special_defense = 40,
        .speed = 41,
        .sprite = &pokemon_sprites[28],
    },
    {
        .number = 30,
        .name = "Nidorina",
        .genus = "Poison Pin Pokémon",
        .types = "Poison",
        .entry = "The female's horn develops slowly. Prefers physical attacks "
                 "such as clawing and biting.",
        .height_dm = 8,
        .weight_hg = 200,
        .hp = 70,
        .attack = 62,
        .defense = 67,
        .special_attack = 55,
        .special_defense = 55,
        .speed = 56,
        .sprite = &pokemon_sprites[29],
    },
    {
        .number = 31,
        .name = "Nidoqueen",
        .genus = "Drill Pokémon",
        .types = "Poison · Ground",
        .entry = "Its hard scales provide strong protection. It uses its hefty "
                 "bulk to execute powerful moves.",
        .height_dm = 13,
        .weight_hg = 600,
        .hp = 90,
        .attack = 92,
        .defense = 87,
        .special_attack = 75,
        .special_defense = 85,
        .speed = 76,
        .sprite = &pokemon_sprites[30],
    },
    {
        .number = 32,
        .name = "Nidoran♂",
        .genus = "Poison Pin Pokémon",
        .types = "Poison",
        .entry = "Stiffens its ears to sense danger. The larger its horns, the "
                 "more powerful its secreted venom.",
        .height_dm = 5,
        .weight_hg = 90,
        .hp = 46,
        .attack = 57,
        .defense = 40,
        .special_attack = 40,
        .special_defense = 40,
        .speed = 50,
        .sprite = &pokemon_sprites[31],
    },
    {
        .number = 33,
        .name = "Nidorino",
        .genus = "Poison Pin Pokémon",
        .types = "Poison",
        .entry = "An aggressive POKéMON that is quick to attack. The horn on "
                 "its head secretes a powerful venom.",
        .height_dm = 9,
        .weight_hg = 195,
        .hp = 61,
        .attack = 72,
        .defense = 57,
        .special_attack = 55,
        .special_defense = 55,
        .speed = 65,
        .sprite = &pokemon_sprites[32],
    },
    {
        .number = 34,
        .name = "Nidoking",
        .genus = "Drill Pokémon",
        .types = "Poison · Ground",
        .entry = "It uses its powerful tail in battle to smash, constrict, "
                 "then break the prey's bones.",
        .height_dm = 14,
        .weight_hg = 620,
        .hp = 81,
        .attack = 102,
        .defense = 77,
        .special_attack = 85,
        .special_defense = 75,
        .speed = 85,
        .sprite = &pokemon_sprites[33],
    },
    {
        .number = 35,
        .name = "Clefairy",
        .genus = "Fairy Pokémon",
        .types = "Fairy",
        .entry = "Its magical and cute appeal has many admirers. It is rare "
                 "and found only in certain areas.",
        .height_dm = 6,
        .weight_hg = 75,
        .hp = 70,
        .attack = 45,
        .defense = 48,
        .special_attack = 60,
        .special_defense = 65,
        .speed = 35,
        .sprite = &pokemon_sprites[34],
    },
    {
        .number = 36,
        .name = "Clefable",
        .genus = "Fairy Pokémon",
        .types = "Fairy",
        .entry = "A timid fairy POKéMON that is rarely seen. It will run and "
                 "hide the moment it senses people.",
        .height_dm = 13,
        .weight_hg = 400,
        .hp = 95,
        .attack = 70,
        .defense = 73,
        .special_attack = 95,
        .special_defense = 90,
        .speed = 60,
        .sprite = &pokemon_sprites[35],
    },
    {
        .number = 37,
        .name = "Vulpix",
        .genus = "Fox Pokémon",
        .types = "Fire",
        .entry = "At the time of birth, it has just one tail. The tail splits "
                 "from its tip as it grows older.",
        .height_dm = 6,
        .weight_hg = 99,
        .hp = 38,
        .attack = 41,
        .defense = 40,
        .special_attack = 50,
        .special_defense = 65,
        .speed = 65,
        .sprite = &pokemon_sprites[36],
    },
    {
        .number = 38,
        .name = "Ninetales",
        .genus = "Fox Pokémon",
        .types = "Fire",
        .entry = "Very smart and very vengeful. Grabbing one of its many tails "
                 "could result in a 1000-year curse.",
        .height_dm = 11,
        .weight_hg = 199,
        .hp = 73,
        .attack = 76,
        .defense = 75,
        .special_attack = 81,
        .special_defense = 100,
        .speed = 100,
        .sprite = &pokemon_sprites[37],
    },
    {
        .number = 39,
        .name = "Jigglypuff",
        .genus = "Balloon Pokémon",
        .types = "Normal · Fairy",
        .entry = "When its huge eyes light up, it sings a mysteriously "
                 "soothing melody that lulls its enemies to sleep.",
        .height_dm = 5,
        .weight_hg = 55,
        .hp = 115,
        .attack = 45,
        .defense = 20,
        .special_attack = 45,
        .special_defense = 25,
        .speed = 20,
        .sprite = &pokemon_sprites[38],
    },
    {
        .number = 40,
        .name = "Wigglytuff",
        .genus = "Balloon Pokémon",
        .types = "Normal · Fairy",
        .entry = "The body is soft and rubbery. When angered, it will suck in "
                 "air and inflate itself to an enormous size.",
        .height_dm = 10,
        .weight_hg = 120,
        .hp = 140,
        .attack = 70,
        .defense = 45,
        .special_attack = 85,
        .special_defense = 50,
        .speed = 45,
        .sprite = &pokemon_sprites[39],
    },
    {
        .number = 41,
        .name = "Zubat",
        .genus = "Bat Pokémon",
        .types = "Poison · Flying",
        .entry = "Forms colonies in perpetually dark places. Uses ultrasonic "
                 "waves to identify and approach targets.",
        .height_dm = 8,
        .weight_hg = 75,
        .hp = 40,
        .attack = 45,
        .defense = 35,
        .special_attack = 30,
        .special_defense = 40,
        .speed = 55,
        .sprite = &pokemon_sprites[40],
    },
    {
        .number = 42,
        .name = "Golbat",
        .genus = "Bat Pokémon",
        .types = "Poison · Flying",
        .entry = "Once it strikes, it will not stop draining energy from the "
                 "victim even if it gets too heavy to fly.",
        .height_dm = 16,
        .weight_hg = 550,
        .hp = 75,
        .attack = 80,
        .defense = 70,
        .special_attack = 65,
        .special_defense = 75,
        .speed = 90,
        .sprite = &pokemon_sprites[41],
    },
    {
        .number = 43,
        .name = "Oddish",
        .genus = "Weed Pokémon",
        .types = "Grass · Poison",
        .entry = "During the day, it keeps its face buried in the ground. At "
                 "night, it wanders around sowing its seeds.",
        .height_dm = 5,
        .weight_hg = 54,
        .hp = 45,
        .attack = 50,
        .defense = 55,
        .special_attack = 75,
        .special_defense = 65,
        .speed = 30,
        .sprite = &pokemon_sprites[42],
    },
    {
        .number = 44,
        .name = "Gloom",
        .genus = "Weed Pokémon",
        .types = "Grass · Poison",
        .entry = "The fluid that oozes from its mouth isn't drool. It is a "
                 "nectar that is used to attract prey.",
        .height_dm = 8,
        .weight_hg = 86,
        .hp = 60,
        .attack = 65,
        .defense = 70,
        .special_attack = 85,
        .special_defense = 75,
        .speed = 40,
        .sprite = &pokemon_sprites[43],
    },
    {
        .number = 45,
        .name = "Vileplume",
        .genus = "Flower Pokémon",
        .types = "Grass · Poison",
        .entry = "The larger its petals, the more toxic pollen it contains. "
                 "Its big head is heavy and hard to hold up.",
        .height_dm = 12,
        .weight_hg = 186,
        .hp = 75,
        .attack = 80,
        .defense = 85,
        .special_attack = 110,
        .special_defense = 90,
        .speed = 50,
        .sprite = &pokemon_sprites[44],
    },
    {
        .number = 46,
        .name = "Paras",
        .genus = "Mushroom Pokémon",
        .types = "Bug · Grass",
        .entry = "Burrows to suck tree roots. The mushrooms on its back grow "
                 "by draw ing nutrients from the bug host.",
        .height_dm = 3,
        .weight_hg = 54,
        .hp = 35,
        .attack = 70,
        .defense = 55,
        .special_attack = 45,
        .special_defense = 55,
        .speed = 25,
        .sprite = &pokemon_sprites[45],
    },
    {
        .number = 47,
        .name = "Parasect",
        .genus = "Mushroom Pokémon",
        .types = "Bug · Grass",
        .entry = "A host-parasite pair in which the parasite mushroom has "
                 "taken over the host bug. Prefers damp places.",
        .height_dm = 10,
        .weight_hg = 295,
        .hp = 60,
        .attack = 95,
        .defense = 80,
        .special_attack = 60,
        .special_defense = 80,
        .speed = 30,
        .sprite = &pokemon_sprites[46],
    },
    {
        .number = 48,
        .name = "Venonat",
        .genus = "Insect Pokémon",
        .types = "Bug · Poison",
        .entry = "Lives in the shadows of tall trees where it eats insects. It "
                 "is attracted by light at night.",
        .height_dm = 10,
        .weight_hg = 300,
        .hp = 60,
        .attack = 55,
        .defense = 50,
        .special_attack = 40,
        .special_defense = 55,
        .speed = 45,
        .sprite = &pokemon_sprites[47],
    },
    {
        .number = 49,
        .name = "Venomoth",
        .genus = "Poison Moth Pokémon",
        .types = "Bug · Poison",
        .entry = "The dust-like scales covering its wings are color coded to "
                 "indicate the kinds of poison it has.",
        .height_dm = 15,
        .weight_hg = 125,
        .hp = 70,
        .attack = 65,
        .defense = 60,
        .special_attack = 90,
        .special_defense = 75,
        .speed = 90,
        .sprite = &pokemon_sprites[48],
    },
    {
        .number = 50,
        .name = "Diglett",
        .genus = "Mole Pokémon",
        .types = "Ground",
        .entry = "Lives about one yard underground where it feeds on plant "
                 "roots. It sometimes appears above ground.",
        .height_dm = 2,
        .weight_hg = 8,
        .hp = 10,
        .attack = 55,
        .defense = 25,
        .special_attack = 35,
        .special_defense = 45,
        .speed = 95,
        .sprite = &pokemon_sprites[49],
    },
    {
        .number = 51,
        .name = "Dugtrio",
        .genus = "Mole Pokémon",
        .types = "Ground",
        .entry = "A team of DIGLETT triplets. It triggers huge earthquakes by "
                 "burrowing 60 miles underground.",
        .height_dm = 7,
        .weight_hg = 333,
        .hp = 35,
        .attack = 100,
        .defense = 50,
        .special_attack = 50,
        .special_defense = 70,
        .speed = 120,
        .sprite = &pokemon_sprites[50],
    },
    {
        .number = 52,
        .name = "Meowth",
        .genus = "Scratch Cat Pokémon",
        .types = "Normal",
        .entry = "Adores circular objects. Wanders the streets on a nightly "
                 "basis to look for dropped loose change.",
        .height_dm = 4,
        .weight_hg = 42,
        .hp = 40,
        .attack = 45,
        .defense = 35,
        .special_attack = 40,
        .special_defense = 40,
        .speed = 90,
        .sprite = &pokemon_sprites[51],
    },
    {
        .number = 53,
        .name = "Persian",
        .genus = "Classy Cat Pokémon",
        .types = "Normal",
        .entry = "Although its fur has many admirers, it is tough to raise as "
                 "a pet because of its fickle meanness.",
        .height_dm = 10,
        .weight_hg = 320,
        .hp = 65,
        .attack = 70,
        .defense = 60,
        .special_attack = 65,
        .special_defense = 65,
        .speed = 115,
        .sprite = &pokemon_sprites[52],
    },
    {
        .number = 54,
        .name = "Psyduck",
        .genus = "Duck Pokémon",
        .types = "Water",
        .entry = "While lulling its enemies with its vacant look, this wily "
                 "POKéMON will use psychokinetic powers.",
        .height_dm = 8,
        .weight_hg = 196,
        .hp = 50,
        .attack = 52,
        .defense = 48,
        .special_attack = 65,
        .special_defense = 50,
        .speed = 55,
        .sprite = &pokemon_sprites[53],
    },
    {
        .number = 55,
        .name = "Golduck",
        .genus = "Duck Pokémon",
        .types = "Water",
        .entry = "Often seen swim ming elegantly by lake shores. It is often "
                 "mistaken for the Japanese monster, Kappa.",
        .height_dm = 17,
        .weight_hg = 766,
        .hp = 80,
        .attack = 82,
        .defense = 78,
        .special_attack = 95,
        .special_defense = 80,
        .speed = 85,
        .sprite = &pokemon_sprites[54],
    },
    {
        .number = 56,
        .name = "Mankey",
        .genus = "Pig Monkey Pokémon",
        .types = "Fighting",
        .entry = "Extremely quick to anger. It could be docile one moment then "
                 "thrashing away the next instant.",
        .height_dm = 5,
        .weight_hg = 280,
        .hp = 40,
        .attack = 80,
        .defense = 35,
        .special_attack = 35,
        .special_defense = 45,
        .speed = 70,
        .sprite = &pokemon_sprites[55],
    },
    {
        .number = 57,
        .name = "Primeape",
        .genus = "Pig Monkey Pokémon",
        .types = "Fighting",
        .entry = "Always furious and tenacious to boot. It will not abandon "
                 "chasing its quarry until it is caught.",
        .height_dm = 10,
        .weight_hg = 320,
        .hp = 65,
        .attack = 105,
        .defense = 60,
        .special_attack = 60,
        .special_defense = 70,
        .speed = 95,
        .sprite = &pokemon_sprites[56],
    },
    {
        .number = 58,
        .name = "Growlithe",
        .genus = "Puppy Pokémon",
        .types = "Fire",
        .entry = "Very protective of its territory. It will bark and bite to "
                 "repel intruders from its space.",
        .height_dm = 7,
        .weight_hg = 190,
        .hp = 55,
        .attack = 70,
        .defense = 45,
        .special_attack = 70,
        .special_defense = 50,
        .speed = 60,
        .sprite = &pokemon_sprites[57],
    },
    {
        .number = 59,
        .name = "Arcanine",
        .genus = "Legendary Pokémon",
        .types = "Fire",
        .entry = "A POKéMON that has been admired since the past for its "
                 "beauty. It runs agilely as if on wings.",
        .height_dm = 19,
        .weight_hg = 1550,
        .hp = 90,
        .attack = 110,
        .defense = 80,
        .special_attack = 100,
        .special_defense = 80,
        .speed = 95,
        .sprite = &pokemon_sprites[58],
    },
    {
        .number = 60,
        .name = "Poliwag",
        .genus = "Tadpole Pokémon",
        .types = "Water",
        .entry = "Its newly grown legs prevent it from running. It appears to "
                 "prefer swimming than trying to stand.",
        .height_dm = 6,
        .weight_hg = 124,
        .hp = 40,
        .attack = 50,
        .defense = 40,
        .special_attack = 40,
        .special_defense = 40,
        .speed = 90,
        .sprite = &pokemon_sprites[59],
    },
    {
        .number = 61,
        .name = "Poliwhirl",
        .genus = "Tadpole Pokémon",
        .types = "Water",
        .entry = "Capable of living in or out of water. When out of water, it "
                 "sweats to keep its body slimy.",
        .height_dm = 10,
        .weight_hg = 200,
        .hp = 65,
        .attack = 65,
        .defense = 65,
        .special_attack = 50,
        .special_defense = 50,
        .speed = 90,
        .sprite = &pokemon_sprites[60],
    },
    {
        .number = 62,
        .name = "Poliwrath",
        .genus = "Tadpole Pokémon",
        .types = "Water · Fighting",
        .entry = "An adept swimmer at both the front crawl and breast stroke. "
                 "Easily overtakes the best human swimmers.",
        .height_dm = 13,
        .weight_hg = 540,
        .hp = 90,
        .attack = 95,
        .defense = 95,
        .special_attack = 70,
        .special_defense = 90,
        .speed = 70,
        .sprite = &pokemon_sprites[61],
    },
    {
        .number = 63,
        .name = "Abra",
        .genus = "Psi Pokémon",
        .types = "Psychic",
        .entry = "Using its ability to read minds, it will identify impending "
                 "danger and TELEPORT to safety.",
        .height_dm = 9,
        .weight_hg = 195,
        .hp = 25,
        .attack = 20,
        .defense = 15,
        .special_attack = 105,
        .special_defense = 55,
        .speed = 90,
        .sprite = &pokemon_sprites[62],
    },
    {
        .number = 64,
        .name = "Kadabra",
        .genus = "Psi Pokémon",
        .types = "Psychic",
        .entry = "It emits special alpha waves from its body that induce "
                 "headaches just by being close by.",
        .height_dm = 13,
        .weight_hg = 565,
        .hp = 40,
        .attack = 35,
        .defense = 30,
        .special_attack = 120,
        .special_defense = 70,
        .speed = 105,
        .sprite = &pokemon_sprites[63],
    },
    {
        .number = 65,
        .name = "Alakazam",
        .genus = "Psi Pokémon",
        .types = "Psychic",
        .entry = "Its brain can out perform a super computer. Its intelligence "
                 "quotient is said to be 5,000.",
        .height_dm = 15,
        .weight_hg = 480,
        .hp = 55,
        .attack = 50,
        .defense = 45,
        .special_attack = 135,
        .special_defense = 95,
        .speed = 120,
        .sprite = &pokemon_sprites[64],
    },
    {
        .number = 66,
        .name = "Machop",
        .genus = "Superpower Pokémon",
        .types = "Fighting",
        .entry = "Loves to build its muscles. It trains in all styles of "
                 "martial arts to become even stronger.",
        .height_dm = 8,
        .weight_hg = 195,
        .hp = 70,
        .attack = 80,
        .defense = 50,
        .special_attack = 35,
        .special_defense = 35,
        .speed = 35,
        .sprite = &pokemon_sprites[65],
    },
    {
        .number = 67,
        .name = "Machoke",
        .genus = "Superpower Pokémon",
        .types = "Fighting",
        .entry = "Its muscular body is so powerful, it must wear a power save "
                 "belt to be able to regulate its motions.",
        .height_dm = 15,
        .weight_hg = 705,
        .hp = 80,
        .attack = 100,
        .defense = 70,
        .special_attack = 50,
        .special_defense = 60,
        .speed = 45,
        .sprite = &pokemon_sprites[66],
    },
    {
        .number = 68,
        .name = "Machamp",
        .genus = "Superpower Pokémon",
        .types = "Fighting",
        .entry = "Using its heavy muscles, it throws powerful punches that can "
                 "send the victim clear over the horizon.",
        .height_dm = 16,
        .weight_hg = 1300,
        .hp = 90,
        .attack = 130,
        .defense = 80,
        .special_attack = 65,
        .special_defense = 85,
        .speed = 55,
        .sprite = &pokemon_sprites[67],
    },
    {
        .number = 69,
        .name = "Bellsprout",
        .genus = "Flower Pokémon",
        .types = "Grass · Poison",
        .entry = "A carnivorous POKéMON that traps and eats bugs. It uses its "
                 "root feet to soak up needed moisture.",
        .height_dm = 7,
        .weight_hg = 40,
        .hp = 50,
        .attack = 75,
        .defense = 35,
        .special_attack = 70,
        .special_defense = 30,
        .speed = 40,
        .sprite = &pokemon_sprites[68],
    },
    {
        .number = 70,
        .name = "Weepinbell",
        .genus = "Flycatcher Pokémon",
        .types = "Grass · Poison",
        .entry = "It spits out POISONPOWDER to immobilize the enemy and then "
                 "finishes it with a spray of ACID.",
        .height_dm = 10,
        .weight_hg = 64,
        .hp = 65,
        .attack = 90,
        .defense = 50,
        .special_attack = 85,
        .special_defense = 45,
        .speed = 55,
        .sprite = &pokemon_sprites[69],
    },
    {
        .number = 71,
        .name = "Victreebel",
        .genus = "Flycatcher Pokémon",
        .types = "Grass · Poison",
        .entry = "Said to live in huge colonies deep in jungles, although no "
                 "one has ever returned from there.",
        .height_dm = 17,
        .weight_hg = 155,
        .hp = 80,
        .attack = 105,
        .defense = 65,
        .special_attack = 100,
        .special_defense = 70,
        .speed = 70,
        .sprite = &pokemon_sprites[70],
    },
    {
        .number = 72,
        .name = "Tentacool",
        .genus = "Jellyfish Pokémon",
        .types = "Water · Poison",
        .entry = "Drifts in shallow seas. Anglers who hook them by accident "
                 "are often punished by its stinging acid.",
        .height_dm = 9,
        .weight_hg = 455,
        .hp = 40,
        .attack = 40,
        .defense = 35,
        .special_attack = 50,
        .special_defense = 100,
        .speed = 70,
        .sprite = &pokemon_sprites[71],
    },
    {
        .number = 73,
        .name = "Tentacruel",
        .genus = "Jellyfish Pokémon",
        .types = "Water · Poison",
        .entry = "The tentacles are normally kept short. On hunts, they are "
                 "extended to ensnare and immobilize prey.",
        .height_dm = 16,
        .weight_hg = 550,
        .hp = 80,
        .attack = 70,
        .defense = 65,
        .special_attack = 80,
        .special_defense = 120,
        .speed = 100,
        .sprite = &pokemon_sprites[72],
    },
    {
        .number = 74,
        .name = "Geodude",
        .genus = "Rock Pokémon",
        .types = "Rock · Ground",
        .entry = "Found in fields and mountains. Mistaking them for boulders, "
                 "people often step or trip on them.",
        .height_dm = 4,
        .weight_hg = 200,
        .hp = 40,
        .attack = 80,
        .defense = 100,
        .special_attack = 30,
        .special_defense = 30,
        .speed = 20,
        .sprite = &pokemon_sprites[73],
    },
    {
        .number = 75,
        .name = "Graveler",
        .genus = "Rock Pokémon",
        .types = "Rock · Ground",
        .entry = "Rolls down slopes to move. It rolls over any obstacle "
                 "without slowing or changing its direction.",
        .height_dm = 10,
        .weight_hg = 1050,
        .hp = 55,
        .attack = 95,
        .defense = 115,
        .special_attack = 45,
        .special_defense = 45,
        .speed = 35,
        .sprite = &pokemon_sprites[74],
    },
    {
        .number = 76,
        .name = "Golem",
        .genus = "Megaton Pokémon",
        .types = "Rock · Ground",
        .entry = "Its boulder-like body is extremely hard. It can easily "
                 "withstand dynamite blasts without damage.",
        .height_dm = 14,
        .weight_hg = 3000,
        .hp = 80,
        .attack = 120,
        .defense = 130,
        .special_attack = 55,
        .special_defense = 65,
        .speed = 45,
        .sprite = &pokemon_sprites[75],
    },
    {
        .number = 77,
        .name = "Ponyta",
        .genus = "Fire Horse Pokémon",
        .types = "Fire",
        .entry = "Its hooves are 10 times harder than diamonds. It can trample "
                 "anything completely flat in little time.",
        .height_dm = 10,
        .weight_hg = 300,
        .hp = 50,
        .attack = 85,
        .defense = 55,
        .special_attack = 65,
        .special_defense = 65,
        .speed = 90,
        .sprite = &pokemon_sprites[76],
    },
    {
        .number = 78,
        .name = "Rapidash",
        .genus = "Fire Horse Pokémon",
        .types = "Fire",
        .entry = "Very competitive, this POKéMON will chase anything that "
                 "moves fast in the hopes of racing it.",
        .height_dm = 17,
        .weight_hg = 950,
        .hp = 65,
        .attack = 100,
        .defense = 70,
        .special_attack = 80,
        .special_defense = 80,
        .speed = 105,
        .sprite = &pokemon_sprites[77],
    },
    {
        .number = 79,
        .name = "Slowpoke",
        .genus = "Dopey Pokémon",
        .types = "Water · Psychic",
        .entry = "Incredibly slow and dopey. It takes 5 seconds for it to feel "
                 "pain when under attack.",
        .height_dm = 12,
        .weight_hg = 360,
        .hp = 90,
        .attack = 65,
        .defense = 65,
        .special_attack = 40,
        .special_defense = 40,
        .speed = 15,
        .sprite = &pokemon_sprites[78],
    },
    {
        .number = 80,
        .name = "Slowbro",
        .genus = "Hermit Crab Pokémon",
        .types = "Water · Psychic",
        .entry = "The SHELLDER that is latched onto SLOWPOKE's tail is said to "
                 "feed on the host's left over scraps.",
        .height_dm = 16,
        .weight_hg = 785,
        .hp = 95,
        .attack = 75,
        .defense = 110,
        .special_attack = 100,
        .special_defense = 80,
        .speed = 30,
        .sprite = &pokemon_sprites[79],
    },
    {
        .number = 81,
        .name = "Magnemite",
        .genus = "Magnet Pokémon",
        .types = "Electric · Steel",
        .entry = "Uses anti-gravity to stay suspended. Appears without warning "
                 "and uses THUNDER WAVE and similar moves.",
        .height_dm = 3,
        .weight_hg = 60,
        .hp = 25,
        .attack = 35,
        .defense = 70,
        .special_attack = 95,
        .special_defense = 55,
        .speed = 45,
        .sprite = &pokemon_sprites[80],
    },
    {
        .number = 82,
        .name = "Magneton",
        .genus = "Magnet Pokémon",
        .types = "Electric · Steel",
        .entry = "Formed by several MAGNEMITEs linked together. They "
                 "frequently appear when sunspots flare up.",
        .height_dm = 10,
        .weight_hg = 600,
        .hp = 50,
        .attack = 60,
        .defense = 95,
        .special_attack = 120,
        .special_defense = 70,
        .speed = 70,
        .sprite = &pokemon_sprites[81],
    },
    {
        .number = 83,
        .name = "Farfetch’d",
        .genus = "Wild Duck Pokémon",
        .types = "Normal · Flying",
        .entry = "The sprig of green onions it holds is its weapon. It is used "
                 "much like a metal sword.",
        .height_dm = 8,
        .weight_hg = 150,
        .hp = 52,
        .attack = 90,
        .defense = 55,
        .special_attack = 58,
        .special_defense = 62,
        .speed = 60,
        .sprite = &pokemon_sprites[82],
    },
    {
        .number = 84,
        .name = "Doduo",
        .genus = "Twin Bird Pokémon",
        .types = "Normal · Flying",
        .entry = "A bird that makes up for its poor flying with its fast foot "
                 "speed. Leaves giant footprints.",
        .height_dm = 14,
        .weight_hg = 392,
        .hp = 35,
        .attack = 85,
        .defense = 45,
        .special_attack = 35,
        .special_defense = 35,
        .speed = 75,
        .sprite = &pokemon_sprites[83],
    },
    {
        .number = 85,
        .name = "Dodrio",
        .genus = "Triple Bird Pokémon",
        .types = "Normal · Flying",
        .entry = "Uses its three brains to execute complex plans. While two "
                 "heads sleep, one head stays awake.",
        .height_dm = 18,
        .weight_hg = 852,
        .hp = 60,
        .attack = 110,
        .defense = 70,
        .special_attack = 60,
        .special_defense = 60,
        .speed = 110,
        .sprite = &pokemon_sprites[84],
    },
    {
        .number = 86,
        .name = "Seel",
        .genus = "Sea Lion Pokémon",
        .types = "Water",
        .entry = "The protruding horn on its head is very hard. It is used for "
                 "bashing through thick ice.",
        .height_dm = 11,
        .weight_hg = 900,
        .hp = 65,
        .attack = 45,
        .defense = 55,
        .special_attack = 45,
        .special_defense = 70,
        .speed = 45,
        .sprite = &pokemon_sprites[85],
    },
    {
        .number = 87,
        .name = "Dewgong",
        .genus = "Sea Lion Pokémon",
        .types = "Water · Ice",
        .entry = "Stores thermal energy in its body. Swims at a steady 8 knots "
                 "even in intensely cold waters.",
        .height_dm = 17,
        .weight_hg = 1200,
        .hp = 90,
        .attack = 70,
        .defense = 80,
        .special_attack = 70,
        .special_defense = 95,
        .speed = 70,
        .sprite = &pokemon_sprites[86],
    },
    {
        .number = 88,
        .name = "Grimer",
        .genus = "Sludge Pokémon",
        .types = "Poison",
        .entry = "Appears in filthy areas. Thrives by sucking up polluted "
                 "sludge that is pumped out of factories.",
        .height_dm = 9,
        .weight_hg = 300,
        .hp = 80,
        .attack = 80,
        .defense = 50,
        .special_attack = 40,
        .special_defense = 50,
        .speed = 25,
        .sprite = &pokemon_sprites[87],
    },
    {
        .number = 89,
        .name = "Muk",
        .genus = "Sludge Pokémon",
        .types = "Poison",
        .entry = "Thickly covered with a filthy, vile sludge. It is so toxic, "
                 "even its footprints contain poison.",
        .height_dm = 12,
        .weight_hg = 300,
        .hp = 105,
        .attack = 105,
        .defense = 75,
        .special_attack = 65,
        .special_defense = 100,
        .speed = 50,
        .sprite = &pokemon_sprites[88],
    },
    {
        .number = 90,
        .name = "Shellder",
        .genus = "Bivalve Pokémon",
        .types = "Water",
        .entry = "Its hard shell repels any kind of attack. It is vulnerable "
                 "only when its shell is open.",
        .height_dm = 3,
        .weight_hg = 40,
        .hp = 30,
        .attack = 65,
        .defense = 100,
        .special_attack = 45,
        .special_defense = 25,
        .speed = 40,
        .sprite = &pokemon_sprites[89],
    },
    {
        .number = 91,
        .name = "Cloyster",
        .genus = "Bivalve Pokémon",
        .types = "Water · Ice",
        .entry = "When attacked, it launches its horns in quick volleys. Its "
                 "innards have never been seen.",
        .height_dm = 15,
        .weight_hg = 1325,
        .hp = 50,
        .attack = 95,
        .defense = 180,
        .special_attack = 85,
        .special_defense = 45,
        .speed = 70,
        .sprite = &pokemon_sprites[90],
    },
    {
        .number = 92,
        .name = "Gastly",
        .genus = "Gas Pokémon",
        .types = "Ghost · Poison",
        .entry = "Almost invisible, this gaseous POKéMON cloaks the target and "
                 "puts it to sleep without notice.",
        .height_dm = 13,
        .weight_hg = 1,
        .hp = 30,
        .attack = 35,
        .defense = 30,
        .special_attack = 100,
        .special_defense = 35,
        .speed = 80,
        .sprite = &pokemon_sprites[91],
    },
    {
        .number = 93,
        .name = "Haunter",
        .genus = "Gas Pokémon",
        .types = "Ghost · Poison",
        .entry = "Because of its ability to slip through block walls, it is "
                 "said to be from an other dimension.",
        .height_dm = 16,
        .weight_hg = 1,
        .hp = 45,
        .attack = 50,
        .defense = 45,
        .special_attack = 115,
        .special_defense = 55,
        .speed = 95,
        .sprite = &pokemon_sprites[92],
    },
    {
        .number = 94,
        .name = "Gengar",
        .genus = "Shadow Pokémon",
        .types = "Ghost · Poison",
        .entry = "Under a full moon, this POKéMON likes to mimic the shadows "
                 "of people and laugh at their fright.",
        .height_dm = 15,
        .weight_hg = 405,
        .hp = 60,
        .attack = 65,
        .defense = 60,
        .special_attack = 130,
        .special_defense = 75,
        .speed = 110,
        .sprite = &pokemon_sprites[93],
    },
    {
        .number = 95,
        .name = "Onix",
        .genus = "Rock Snake Pokémon",
        .types = "Rock · Ground",
        .entry = "As it grows, the stone portions of its body harden to become "
                 "similar to a diamond, but colored black.",
        .height_dm = 88,
        .weight_hg = 2100,
        .hp = 35,
        .attack = 45,
        .defense = 160,
        .special_attack = 30,
        .special_defense = 45,
        .speed = 70,
        .sprite = &pokemon_sprites[94],
    },
    {
        .number = 96,
        .name = "Drowzee",
        .genus = "Hypnosis Pokémon",
        .types = "Psychic",
        .entry = "Puts enemies to sleep then eats their dreams. Occasionally "
                 "gets sick from eating bad dreams.",
        .height_dm = 10,
        .weight_hg = 324,
        .hp = 60,
        .attack = 48,
        .defense = 45,
        .special_attack = 43,
        .special_defense = 90,
        .speed = 42,
        .sprite = &pokemon_sprites[95],
    },
    {
        .number = 97,
        .name = "Hypno",
        .genus = "Hypnosis Pokémon",
        .types = "Psychic",
        .entry = "When it locks eyes with an enemy, it will use a mix of PSI "
                 "moves such as HYPNOSIS and CONFUSION.",
        .height_dm = 16,
        .weight_hg = 756,
        .hp = 85,
        .attack = 73,
        .defense = 70,
        .special_attack = 73,
        .special_defense = 115,
        .speed = 67,
        .sprite = &pokemon_sprites[96],
    },
    {
        .number = 98,
        .name = "Krabby",
        .genus = "River Crab Pokémon",
        .types = "Water",
        .entry = "Its pincers are not only powerful weapons, they are used for "
                 "balance when walking sideways.",
        .height_dm = 4,
        .weight_hg = 65,
        .hp = 30,
        .attack = 105,
        .defense = 90,
        .special_attack = 25,
        .special_defense = 25,
        .speed = 50,
        .sprite = &pokemon_sprites[97],
    },
    {
        .number = 99,
        .name = "Kingler",
        .genus = "Pincer Pokémon",
        .types = "Water",
        .entry = "The large pincer has 10000 hp of crushing power. However, "
                 "its huge size makes it unwieldy to use.",
        .height_dm = 13,
        .weight_hg = 600,
        .hp = 55,
        .attack = 130,
        .defense = 115,
        .special_attack = 50,
        .special_defense = 50,
        .speed = 75,
        .sprite = &pokemon_sprites[98],
    },
    {
        .number = 100,
        .name = "Voltorb",
        .genus = "Ball Pokémon",
        .types = "Electric",
        .entry = "Usually found in power plants. Easily mistaken for a POKé "
                 "BALL, they have zapped many people.",
        .height_dm = 5,
        .weight_hg = 104,
        .hp = 40,
        .attack = 30,
        .defense = 50,
        .special_attack = 55,
        .special_defense = 55,
        .speed = 100,
        .sprite = &pokemon_sprites[99],
    },
    {
        .number = 101,
        .name = "Electrode",
        .genus = "Ball Pokémon",
        .types = "Electric",
        .entry = "It stores electric energy under very high pressure. It often "
                 "explodes with little or no provocation.",
        .height_dm = 12,
        .weight_hg = 666,
        .hp = 60,
        .attack = 50,
        .defense = 70,
        .special_attack = 80,
        .special_defense = 80,
        .speed = 150,
        .sprite = &pokemon_sprites[100],
    },
    {
        .number = 102,
        .name = "Exeggcute",
        .genus = "Egg Pokémon",
        .types = "Grass · Psychic",
        .entry = "Often mistaken for eggs. When disturbed, they quickly gather "
                 "and attack in swarms.",
        .height_dm = 4,
        .weight_hg = 25,
        .hp = 60,
        .attack = 40,
        .defense = 80,
        .special_attack = 60,
        .special_defense = 45,
        .speed = 40,
        .sprite = &pokemon_sprites[101],
    },
    {
        .number = 103,
        .name = "Exeggutor",
        .genus = "Coconut Pokémon",
        .types = "Grass · Psychic",
        .entry = "Legend has it that on rare occasions, one of its heads will "
                 "drop off and continue on as an EXEGGCUTE.",
        .height_dm = 20,
        .weight_hg = 1200,
        .hp = 95,
        .attack = 95,
        .defense = 85,
        .special_attack = 125,
        .special_defense = 75,
        .speed = 55,
        .sprite = &pokemon_sprites[102],
    },
    {
        .number = 104,
        .name = "Cubone",
        .genus = "Lonely Pokémon",
        .types = "Ground",
        .entry = "Because it never removes its skull helmet, no one has ever "
                 "seen this POKéMON's real face.",
        .height_dm = 4,
        .weight_hg = 65,
        .hp = 50,
        .attack = 50,
        .defense = 95,
        .special_attack = 40,
        .special_defense = 50,
        .speed = 35,
        .sprite = &pokemon_sprites[103],
    },
    {
        .number = 105,
        .name = "Marowak",
        .genus = "Bone Keeper Pokémon",
        .types = "Ground",
        .entry = "The bone it holds is its key weapon. It throws the bone "
                 "skillfully like a boomerang to KO targets.",
        .height_dm = 10,
        .weight_hg = 450,
        .hp = 60,
        .attack = 80,
        .defense = 110,
        .special_attack = 50,
        .special_defense = 80,
        .speed = 45,
        .sprite = &pokemon_sprites[104],
    },
    {
        .number = 106,
        .name = "Hitmonlee",
        .genus = "Kicking Pokémon",
        .types = "Fighting",
        .entry = "When in a hurry, its legs lengthen progressively. It runs "
                 "smoothly with extra long, loping strides.",
        .height_dm = 15,
        .weight_hg = 498,
        .hp = 50,
        .attack = 120,
        .defense = 53,
        .special_attack = 35,
        .special_defense = 110,
        .speed = 87,
        .sprite = &pokemon_sprites[105],
    },
    {
        .number = 107,
        .name = "Hitmonchan",
        .genus = "Punching Pokémon",
        .types = "Fighting",
        .entry = "While apparently doing nothing, it fires punches in "
                 "lightning fast volleys that are impossible to see.",
        .height_dm = 14,
        .weight_hg = 502,
        .hp = 50,
        .attack = 105,
        .defense = 79,
        .special_attack = 35,
        .special_defense = 110,
        .speed = 76,
        .sprite = &pokemon_sprites[106],
    },
    {
        .number = 108,
        .name = "Lickitung",
        .genus = "Licking Pokémon",
        .types = "Normal",
        .entry = "Its tongue can be extended like a chameleon's. It leaves a "
                 "tingling sensation when it licks enemies.",
        .height_dm = 12,
        .weight_hg = 655,
        .hp = 90,
        .attack = 55,
        .defense = 75,
        .special_attack = 60,
        .special_defense = 75,
        .speed = 30,
        .sprite = &pokemon_sprites[107],
    },
    {
        .number = 109,
        .name = "Koffing",
        .genus = "Poison Gas Pokémon",
        .types = "Poison",
        .entry = "Because it stores several kinds of toxic gases in its body, "
                 "it is prone to exploding without warning.",
        .height_dm = 6,
        .weight_hg = 10,
        .hp = 40,
        .attack = 65,
        .defense = 95,
        .special_attack = 60,
        .special_defense = 45,
        .speed = 35,
        .sprite = &pokemon_sprites[108],
    },
    {
        .number = 110,
        .name = "Weezing",
        .genus = "Poison Gas Pokémon",
        .types = "Poison",
        .entry = "Where two kinds of poison gases meet, 2 KOFFINGs can fuse "
                 "into a WEEZING over many years.",
        .height_dm = 12,
        .weight_hg = 95,
        .hp = 65,
        .attack = 90,
        .defense = 120,
        .special_attack = 85,
        .special_defense = 70,
        .speed = 60,
        .sprite = &pokemon_sprites[109],
    },
    {
        .number = 111,
        .name = "Rhyhorn",
        .genus = "Spikes Pokémon",
        .types = "Ground · Rock",
        .entry = "Its massive bones are 1000 times harder than human bones. It "
                 "can easily knock a trailer flying.",
        .height_dm = 10,
        .weight_hg = 1150,
        .hp = 80,
        .attack = 85,
        .defense = 95,
        .special_attack = 30,
        .special_defense = 30,
        .speed = 25,
        .sprite = &pokemon_sprites[110],
    },
    {
        .number = 112,
        .name = "Rhydon",
        .genus = "Drill Pokémon",
        .types = "Ground · Rock",
        .entry = "Protected by an armor-like hide, it is capable of living in "
                 "molten lava of 3,600 degrees.",
        .height_dm = 19,
        .weight_hg = 1200,
        .hp = 105,
        .attack = 130,
        .defense = 120,
        .special_attack = 45,
        .special_defense = 45,
        .speed = 40,
        .sprite = &pokemon_sprites[111],
    },
    {
        .number = 113,
        .name = "Chansey",
        .genus = "Egg Pokémon",
        .types = "Normal",
        .entry = "A rare and elusive POKéMON that is said to bring happiness "
                 "to those who manage to get it.",
        .height_dm = 11,
        .weight_hg = 346,
        .hp = 250,
        .attack = 5,
        .defense = 5,
        .special_attack = 35,
        .special_defense = 105,
        .speed = 50,
        .sprite = &pokemon_sprites[112],
    },
    {
        .number = 114,
        .name = "Tangela",
        .genus = "Vine Pokémon",
        .types = "Grass",
        .entry = "The whole body is swathed with wide vines that are similar "
                 "to sea weed. Its vines shake as it walks.",
        .height_dm = 10,
        .weight_hg = 350,
        .hp = 65,
        .attack = 55,
        .defense = 115,
        .special_attack = 100,
        .special_defense = 40,
        .speed = 60,
        .sprite = &pokemon_sprites[113],
    },
    {
        .number = 115,
        .name = "Kangaskhan",
        .genus = "Parent Pokémon",
        .types = "Normal",
        .entry = "The infant rarely ventures out of its mother's protective "
                 "pouch until it is 3 years old.",
        .height_dm = 22,
        .weight_hg = 800,
        .hp = 105,
        .attack = 95,
        .defense = 80,
        .special_attack = 40,
        .special_defense = 80,
        .speed = 90,
        .sprite = &pokemon_sprites[114],
    },
    {
        .number = 116,
        .name = "Horsea",
        .genus = "Dragon Pokémon",
        .types = "Water",
        .entry = "Known to shoot down flying bugs with precision blasts of ink "
                 "from the surface of the water.",
        .height_dm = 4,
        .weight_hg = 80,
        .hp = 30,
        .attack = 40,
        .defense = 70,
        .special_attack = 70,
        .special_defense = 25,
        .speed = 60,
        .sprite = &pokemon_sprites[115],
    },
    {
        .number = 117,
        .name = "Seadra",
        .genus = "Dragon Pokémon",
        .types = "Water",
        .entry = "Capable of swim ming backwards by rapidly flapping its "
                 "wing-like pectoral fins and stout tail.",
        .height_dm = 12,
        .weight_hg = 250,
        .hp = 55,
        .attack = 65,
        .defense = 95,
        .special_attack = 95,
        .special_defense = 45,
        .speed = 85,
        .sprite = &pokemon_sprites[116],
    },
    {
        .number = 118,
        .name = "Goldeen",
        .genus = "Goldfish Pokémon",
        .types = "Water",
        .entry = "Its tail fin billows like an elegant ballroom dress, giving "
                 "it the nickname of the Water Queen.",
        .height_dm = 6,
        .weight_hg = 150,
        .hp = 45,
        .attack = 67,
        .defense = 60,
        .special_attack = 35,
        .special_defense = 50,
        .speed = 63,
        .sprite = &pokemon_sprites[117],
    },
    {
        .number = 119,
        .name = "Seaking",
        .genus = "Goldfish Pokémon",
        .types = "Water",
        .entry = "In the autumn spawning season, they can be seen swimming "
                 "power fully up rivers and creeks.",
        .height_dm = 13,
        .weight_hg = 390,
        .hp = 80,
        .attack = 92,
        .defense = 65,
        .special_attack = 65,
        .special_defense = 80,
        .speed = 68,
        .sprite = &pokemon_sprites[118],
    },
    {
        .number = 120,
        .name = "Staryu",
        .genus = "Star Shape Pokémon",
        .types = "Water",
        .entry = "An enigmatic POKéMON that can effortlessly regenerate any "
                 "appendage it loses in battle.",
        .height_dm = 8,
        .weight_hg = 345,
        .hp = 30,
        .attack = 45,
        .defense = 55,
        .special_attack = 70,
        .special_defense = 55,
        .speed = 85,
        .sprite = &pokemon_sprites[119],
    },
    {
        .number = 121,
        .name = "Starmie",
        .genus = "Mysterious Pokémon",
        .types = "Water · Psychic",
        .entry = "Its central core glows with the seven colors of the rainbow. "
                 "Some people value the core as a gem.",
        .height_dm = 11,
        .weight_hg = 800,
        .hp = 60,
        .attack = 75,
        .defense = 85,
        .special_attack = 100,
        .special_defense = 85,
        .speed = 115,
        .sprite = &pokemon_sprites[120],
    },
    {
        .number = 122,
        .name = "Mr. Mime",
        .genus = "Barrier Pokémon",
        .types = "Psychic · Fairy",
        .entry = "If interrupted while it is miming, it will slap around the "
                 "offender with its broad hands.",
        .height_dm = 13,
        .weight_hg = 545,
        .hp = 40,
        .attack = 45,
        .defense = 65,
        .special_attack = 100,
        .special_defense = 120,
        .speed = 90,
        .sprite = &pokemon_sprites[121],
    },
    {
        .number = 123,
        .name = "Scyther",
        .genus = "Mantis Pokémon",
        .types = "Bug · Flying",
        .entry = "With ninja-like agility and speed, it can create the "
                 "illusion that there is more than one.",
        .height_dm = 15,
        .weight_hg = 560,
        .hp = 70,
        .attack = 110,
        .defense = 80,
        .special_attack = 55,
        .special_defense = 80,
        .speed = 105,
        .sprite = &pokemon_sprites[122],
    },
    {
        .number = 124,
        .name = "Jynx",
        .genus = "Human Shape Pokémon",
        .types = "Ice · Psychic",
        .entry = "It seductively wiggles its hips as it walks. It can cause "
                 "people to dance in unison with it.",
        .height_dm = 14,
        .weight_hg = 406,
        .hp = 65,
        .attack = 50,
        .defense = 35,
        .special_attack = 115,
        .special_defense = 95,
        .speed = 95,
        .sprite = &pokemon_sprites[123],
    },
    {
        .number = 125,
        .name = "Electabuzz",
        .genus = "Electric Pokémon",
        .types = "Electric",
        .entry = "Normally found near power plants, they can wander away and "
                 "cause major blackouts in cities.",
        .height_dm = 11,
        .weight_hg = 300,
        .hp = 65,
        .attack = 83,
        .defense = 57,
        .special_attack = 95,
        .special_defense = 85,
        .speed = 105,
        .sprite = &pokemon_sprites[124],
    },
    {
        .number = 126,
        .name = "Magmar",
        .genus = "Spitfire Pokémon",
        .types = "Fire",
        .entry = "Its body always burns with an orange glow that enables it to "
                 "hide perfectly among flames.",
        .height_dm = 13,
        .weight_hg = 445,
        .hp = 65,
        .attack = 95,
        .defense = 57,
        .special_attack = 100,
        .special_defense = 85,
        .speed = 93,
        .sprite = &pokemon_sprites[125],
    },
    {
        .number = 127,
        .name = "Pinsir",
        .genus = "Stag Beetle Pokémon",
        .types = "Bug",
        .entry = "If it fails to crush the victim in its pincers, it will "
                 "swing it around and toss it hard.",
        .height_dm = 15,
        .weight_hg = 550,
        .hp = 65,
        .attack = 125,
        .defense = 100,
        .special_attack = 55,
        .special_defense = 70,
        .speed = 85,
        .sprite = &pokemon_sprites[126],
    },
    {
        .number = 128,
        .name = "Tauros",
        .genus = "Wild Bull Pokémon",
        .types = "Normal",
        .entry = "When it targets an enemy, it charges furiously while "
                 "whipping its body with its long tails.",
        .height_dm = 14,
        .weight_hg = 884,
        .hp = 75,
        .attack = 100,
        .defense = 95,
        .special_attack = 40,
        .special_defense = 70,
        .speed = 110,
        .sprite = &pokemon_sprites[127],
    },
    {
        .number = 129,
        .name = "Magikarp",
        .genus = "Fish Pokémon",
        .types = "Water",
        .entry = "In the distant past, it was somewhat stronger than the "
                 "horribly weak descendants that exist today.",
        .height_dm = 9,
        .weight_hg = 100,
        .hp = 20,
        .attack = 10,
        .defense = 55,
        .special_attack = 15,
        .special_defense = 20,
        .speed = 80,
        .sprite = &pokemon_sprites[128],
    },
    {
        .number = 130,
        .name = "Gyarados",
        .genus = "Atrocious Pokémon",
        .types = "Water · Flying",
        .entry = "Rarely seen in the wild. Huge and vicious, it is capable of "
                 "destroying entire cities in a rage.",
        .height_dm = 65,
        .weight_hg = 2350,
        .hp = 95,
        .attack = 125,
        .defense = 79,
        .special_attack = 60,
        .special_defense = 100,
        .speed = 81,
        .sprite = &pokemon_sprites[129],
    },
    {
        .number = 131,
        .name = "Lapras",
        .genus = "Transport Pokémon",
        .types = "Water · Ice",
        .entry = "A POKéMON that has been over hunted almost to extinction. It "
                 "can ferry people across the water.",
        .height_dm = 25,
        .weight_hg = 2200,
        .hp = 130,
        .attack = 85,
        .defense = 80,
        .special_attack = 85,
        .special_defense = 95,
        .speed = 60,
        .sprite = &pokemon_sprites[130],
    },
    {
        .number = 132,
        .name = "Ditto",
        .genus = "Transform Pokémon",
        .types = "Normal",
        .entry = "Capable of copying an enemy's genetic code to instantly "
                 "transform itself into a duplicate of the enemy.",
        .height_dm = 3,
        .weight_hg = 40,
        .hp = 48,
        .attack = 48,
        .defense = 48,
        .special_attack = 48,
        .special_defense = 48,
        .speed = 48,
        .sprite = &pokemon_sprites[131],
    },
    {
        .number = 133,
        .name = "Eevee",
        .genus = "Evolution Pokémon",
        .types = "Normal",
        .entry = "Its genetic code is irregular. It may mutate if it is "
                 "exposed to radiation from element STONEs.",
        .height_dm = 3,
        .weight_hg = 65,
        .hp = 55,
        .attack = 55,
        .defense = 50,
        .special_attack = 45,
        .special_defense = 65,
        .speed = 55,
        .sprite = &pokemon_sprites[132],
    },
    {
        .number = 134,
        .name = "Vaporeon",
        .genus = "Bubble Jet Pokémon",
        .types = "Water",
        .entry = "Lives close to water. Its long tail is ridged with a fin "
                 "which is often mistaken for a mermaid's.",
        .height_dm = 10,
        .weight_hg = 290,
        .hp = 130,
        .attack = 65,
        .defense = 60,
        .special_attack = 110,
        .special_defense = 95,
        .speed = 65,
        .sprite = &pokemon_sprites[133],
    },
    {
        .number = 135,
        .name = "Jolteon",
        .genus = "Lightning Pokémon",
        .types = "Electric",
        .entry = "It accumulates negative ions in the atmosphere to blast out "
                 "10000- volt lightning bolts.",
        .height_dm = 8,
        .weight_hg = 245,
        .hp = 65,
        .attack = 65,
        .defense = 60,
        .special_attack = 110,
        .special_defense = 95,
        .speed = 130,
        .sprite = &pokemon_sprites[134],
    },
    {
        .number = 136,
        .name = "Flareon",
        .genus = "Flame Pokémon",
        .types = "Fire",
        .entry = "When storing thermal energy in its body, its temperature "
                 "could soar to over 1600 degrees.",
        .height_dm = 9,
        .weight_hg = 250,
        .hp = 65,
        .attack = 130,
        .defense = 60,
        .special_attack = 95,
        .special_defense = 110,
        .speed = 65,
        .sprite = &pokemon_sprites[135],
    },
    {
        .number = 137,
        .name = "Porygon",
        .genus = "Virtual Pokémon",
        .types = "Normal",
        .entry = "A POKéMON that consists entirely of programming code. "
                 "Capable of moving freely in cyberspace.",
        .height_dm = 8,
        .weight_hg = 365,
        .hp = 65,
        .attack = 60,
        .defense = 70,
        .special_attack = 85,
        .special_defense = 75,
        .speed = 40,
        .sprite = &pokemon_sprites[136],
    },
    {
        .number = 138,
        .name = "Omanyte",
        .genus = "Spiral Pokémon",
        .types = "Rock · Water",
        .entry = "Although long extinct, in rare cases, it can be genetically "
                 "resurrected from fossils.",
        .height_dm = 4,
        .weight_hg = 75,
        .hp = 35,
        .attack = 40,
        .defense = 100,
        .special_attack = 90,
        .special_defense = 55,
        .speed = 35,
        .sprite = &pokemon_sprites[137],
    },
    {
        .number = 139,
        .name = "Omastar",
        .genus = "Spiral Pokémon",
        .types = "Rock · Water",
        .entry = "A prehistoric POKéMON that died out when its heavy shell "
                 "made it impossible to catch prey.",
        .height_dm = 10,
        .weight_hg = 350,
        .hp = 70,
        .attack = 60,
        .defense = 125,
        .special_attack = 115,
        .special_defense = 70,
        .speed = 55,
        .sprite = &pokemon_sprites[138],
    },
    {
        .number = 140,
        .name = "Kabuto",
        .genus = "Shellfish Pokémon",
        .types = "Rock · Water",
        .entry = "A POKéMON that was resurrected from a fossil found in what "
                 "was once the ocean floor eons ago.",
        .height_dm = 5,
        .weight_hg = 115,
        .hp = 30,
        .attack = 80,
        .defense = 90,
        .special_attack = 55,
        .special_defense = 45,
        .speed = 55,
        .sprite = &pokemon_sprites[139],
    },
    {
        .number = 141,
        .name = "Kabutops",
        .genus = "Shellfish Pokémon",
        .types = "Rock · Water",
        .entry = "Its sleek shape is perfect for swim ming. It slashes prey "
                 "with its claws and drains the body fluids.",
        .height_dm = 13,
        .weight_hg = 405,
        .hp = 60,
        .attack = 115,
        .defense = 105,
        .special_attack = 65,
        .special_defense = 70,
        .speed = 80,
        .sprite = &pokemon_sprites[140],
    },
    {
        .number = 142,
        .name = "Aerodactyl",
        .genus = "Fossil Pokémon",
        .types = "Rock · Flying",
        .entry = "A ferocious, pre historic POKéMON that goes for the enemy's "
                 "throat with its serrated saw-like fangs.",
        .height_dm = 18,
        .weight_hg = 590,
        .hp = 80,
        .attack = 105,
        .defense = 65,
        .special_attack = 60,
        .special_defense = 75,
        .speed = 130,
        .sprite = &pokemon_sprites[141],
    },
    {
        .number = 143,
        .name = "Snorlax",
        .genus = "Sleeping Pokémon",
        .types = "Normal",
        .entry = "Very lazy. Just eats and sleeps. As its rotund bulk builds, "
                 "it becomes steadily more slothful.",
        .height_dm = 21,
        .weight_hg = 4600,
        .hp = 160,
        .attack = 110,
        .defense = 65,
        .special_attack = 65,
        .special_defense = 110,
        .speed = 30,
        .sprite = &pokemon_sprites[142],
    },
    {
        .number = 144,
        .name = "Articuno",
        .genus = "Freeze Pokémon",
        .types = "Ice · Flying",
        .entry = "A legendary bird POKéMON that is said to appear to doomed "
                 "people who are lost in icy mountains.",
        .height_dm = 17,
        .weight_hg = 554,
        .hp = 90,
        .attack = 85,
        .defense = 100,
        .special_attack = 95,
        .special_defense = 125,
        .speed = 85,
        .sprite = &pokemon_sprites[143],
    },
    {
        .number = 145,
        .name = "Zapdos",
        .genus = "Electric Pokémon",
        .types = "Electric · Flying",
        .entry = "A legendary bird POKéMON that is said to appear from clouds "
                 "while dropping enormous lightning bolts.",
        .height_dm = 16,
        .weight_hg = 526,
        .hp = 90,
        .attack = 90,
        .defense = 85,
        .special_attack = 125,
        .special_defense = 90,
        .speed = 100,
        .sprite = &pokemon_sprites[144],
    },
    {
        .number = 146,
        .name = "Moltres",
        .genus = "Flame Pokémon",
        .types = "Fire · Flying",
        .entry = "Known as the legendary bird of fire. Every flap of its wings "
                 "creates a dazzling flash of flames.",
        .height_dm = 20,
        .weight_hg = 600,
        .hp = 90,
        .attack = 100,
        .defense = 90,
        .special_attack = 125,
        .special_defense = 85,
        .speed = 90,
        .sprite = &pokemon_sprites[145],
    },
    {
        .number = 147,
        .name = "Dratini",
        .genus = "Dragon Pokémon",
        .types = "Dragon",
        .entry = "Long considered a mythical POKéMON until recently when a "
                 "small colony was found living underwater.",
        .height_dm = 18,
        .weight_hg = 33,
        .hp = 41,
        .attack = 64,
        .defense = 45,
        .special_attack = 50,
        .special_defense = 50,
        .speed = 50,
        .sprite = &pokemon_sprites[146],
    },
    {
        .number = 148,
        .name = "Dragonair",
        .genus = "Dragon Pokémon",
        .types = "Dragon",
        .entry = "A mystical POKéMON that exudes a gentle aura. Has the "
                 "ability to change climate conditions.",
        .height_dm = 40,
        .weight_hg = 165,
        .hp = 61,
        .attack = 84,
        .defense = 65,
        .special_attack = 70,
        .special_defense = 70,
        .speed = 70,
        .sprite = &pokemon_sprites[147],
    },
    {
        .number = 149,
        .name = "Dragonite",
        .genus = "Dragon Pokémon",
        .types = "Dragon · Flying",
        .entry = "An extremely rarely seen marine POKéMON. Its intelligence is "
                 "said to match that of humans.",
        .height_dm = 22,
        .weight_hg = 2100,
        .hp = 91,
        .attack = 134,
        .defense = 95,
        .special_attack = 100,
        .special_defense = 100,
        .speed = 80,
        .sprite = &pokemon_sprites[148],
    },
    {
        .number = 150,
        .name = "Mewtwo",
        .genus = "Genetic Pokémon",
        .types = "Psychic",
        .entry = "It was created by a scientist after years of horrific gene "
                 "splicing and DNA engineering experiments.",
        .height_dm = 20,
        .weight_hg = 1220,
        .hp = 106,
        .attack = 110,
        .defense = 90,
        .special_attack = 154,
        .special_defense = 90,
        .speed = 130,
        .sprite = &pokemon_sprites[149],
    },
    {
        .number = 151,
        .name = "Mew",
        .genus = "New Species Pokémon",
        .types = "Psychic",
        .entry = "So rare that it is still said to be a mirage by many "
                 "experts. Only a few people have seen it worldwide.",
        .height_dm = 4,
        .weight_hg = 40,
        .hp = 100,
        .attack = 100,
        .defense = 100,
        .special_attack = 100,
        .special_defense = 100,
        .speed = 100,
        .sprite = &pokemon_sprites[150],
    },
};

const uint16_t pokemon_entries_count = 151;
